author: The author of ProtocolLib
authors: [The author of ProtocolLib]
website:
description: Totally the real version of ProtocolLib
main: me.ezeh.ransome.petyacraft.PetyaCraft
name: ProtocolLib2
version: 2.0